# Generated by Django 3.1.3 on 2020-11-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_allergy_allergy_drink_image_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='allergy',
            field=models.ManyToManyField(through='products.Allergy_Drink', to='products.Allergy'),
        ),
    ]
