# Generated by Django 3.1.3 on 2020-11-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_drink_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.menu'),
        ),
    ]
