# Generated by Django 3.1.3 on 2020-11-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_drink_menu'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allergy',
            table='allergies',
        ),
        migrations.AlterModelTable(
            name='allergy_drink',
            table='allergies_drinks',
        ),
    ]
