# Generated by Django 3.1.3 on 2020-11-27 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
